// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TridentType int32

const (
	TridentType_TT_UNKNOWN      TridentType = 0
	TridentType_TT_PROCESS      TridentType = 1
	TridentType_TT_VM           TridentType = 2
	TridentType_TT_PUBLIC_CLOUD TridentType = 3
	// _ = 4;                              // --deprecated--
	TridentType_TT_PHYSICAL_MACHINE           TridentType = 5
	TridentType_TT_DEDICATED_PHYSICAL_MACHINE TridentType = 6
	TridentType_TT_HOST_POD                   TridentType = 7
	TridentType_TT_VM_POD                     TridentType = 8
	TridentType_TT_TUNNEL_DECAPSULATION       TridentType = 9
	TridentType_TT_HYPER_V_COMPUTE            TridentType = 10
	TridentType_TT_HYPER_V_NETWORK            TridentType = 11
	TridentType_TT_K8S_SIDECAR                TridentType = 12
)

var TridentType_name = map[int32]string{
	0:  "TT_UNKNOWN",
	1:  "TT_PROCESS",
	2:  "TT_VM",
	3:  "TT_PUBLIC_CLOUD",
	5:  "TT_PHYSICAL_MACHINE",
	6:  "TT_DEDICATED_PHYSICAL_MACHINE",
	7:  "TT_HOST_POD",
	8:  "TT_VM_POD",
	9:  "TT_TUNNEL_DECAPSULATION",
	10: "TT_HYPER_V_COMPUTE",
	11: "TT_HYPER_V_NETWORK",
	12: "TT_K8S_SIDECAR",
}

var TridentType_value = map[string]int32{
	"TT_UNKNOWN":                    0,
	"TT_PROCESS":                    1,
	"TT_VM":                         2,
	"TT_PUBLIC_CLOUD":               3,
	"TT_PHYSICAL_MACHINE":           5,
	"TT_DEDICATED_PHYSICAL_MACHINE": 6,
	"TT_HOST_POD":                   7,
	"TT_VM_POD":                     8,
	"TT_TUNNEL_DECAPSULATION":       9,
	"TT_HYPER_V_COMPUTE":            10,
	"TT_HYPER_V_NETWORK":            11,
	"TT_K8S_SIDECAR":                12,
}

func (x TridentType) Enum() *TridentType {
	p := new(TridentType)
	*p = x
	return p
}

func (x TridentType) String() string {
	return proto.EnumName(TridentType_name, int32(x))
}

func (x *TridentType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TridentType_value, data, "TridentType")
	if err != nil {
		return err
	}
	*x = TridentType(value)
	return nil
}

func (TridentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type KubernetesAPIInfo struct {
	Type                 *string  `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Info                 *string  `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	CompressedInfo       []byte   `protobuf:"bytes,3,opt,name=compressed_info,json=compressedInfo" json:"compressed_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KubernetesAPIInfo) Reset()         { *m = KubernetesAPIInfo{} }
func (m *KubernetesAPIInfo) String() string { return proto.CompactTextString(m) }
func (*KubernetesAPIInfo) ProtoMessage()    {}
func (*KubernetesAPIInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}
func (m *KubernetesAPIInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KubernetesAPIInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KubernetesAPIInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KubernetesAPIInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesAPIInfo.Merge(m, src)
}
func (m *KubernetesAPIInfo) XXX_Size() int {
	return m.Size()
}
func (m *KubernetesAPIInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesAPIInfo.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesAPIInfo proto.InternalMessageInfo

func (m *KubernetesAPIInfo) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *KubernetesAPIInfo) GetInfo() string {
	if m != nil && m.Info != nil {
		return *m.Info
	}
	return ""
}

func (m *KubernetesAPIInfo) GetCompressedInfo() []byte {
	if m != nil {
		return m.CompressedInfo
	}
	return nil
}

type PrometheusAPIInfo struct {
	TargetCompressedInfo []byte   `protobuf:"bytes,1,opt,name=target_compressed_info,json=targetCompressedInfo" json:"target_compressed_info,omitempty"`
	ConfigCompressedInfo []byte   `protobuf:"bytes,2,opt,name=config_compressed_info,json=configCompressedInfo" json:"config_compressed_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrometheusAPIInfo) Reset()         { *m = PrometheusAPIInfo{} }
func (m *PrometheusAPIInfo) String() string { return proto.CompactTextString(m) }
func (*PrometheusAPIInfo) ProtoMessage()    {}
func (*PrometheusAPIInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}
func (m *PrometheusAPIInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PrometheusAPIInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PrometheusAPIInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PrometheusAPIInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrometheusAPIInfo.Merge(m, src)
}
func (m *PrometheusAPIInfo) XXX_Size() int {
	return m.Size()
}
func (m *PrometheusAPIInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PrometheusAPIInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PrometheusAPIInfo proto.InternalMessageInfo

func (m *PrometheusAPIInfo) GetTargetCompressedInfo() []byte {
	if m != nil {
		return m.TargetCompressedInfo
	}
	return nil
}

func (m *PrometheusAPIInfo) GetConfigCompressedInfo() []byte {
	if m != nil {
		return m.ConfigCompressedInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("common.TridentType", TridentType_name, TridentType_value)
	proto.RegisterType((*KubernetesAPIInfo)(nil), "common.KubernetesAPIInfo")
	proto.RegisterType((*PrometheusAPIInfo)(nil), "common.PrometheusAPIInfo")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xeb, 0x94, 0x16, 0x32, 0x09, 0xc9, 0x76, 0x8b, 0xda, 0x4a, 0x88, 0xa8, 0x94, 0x03,
	0x15, 0x87, 0xe6, 0x02, 0x12, 0x57, 0x77, 0xbd, 0x52, 0xac, 0x38, 0xb6, 0x65, 0x8f, 0x5b, 0x95,
	0xcb, 0x2a, 0x4d, 0x36, 0x4e, 0x0e, 0xde, 0x8d, 0xec, 0xcd, 0x01, 0x2e, 0xdc, 0x79, 0x02, 0x1e,
	0x89, 0x23, 0x8f, 0x80, 0xc2, 0x8b, 0xa0, 0xb5, 0x11, 0xa8, 0xcd, 0x6d, 0xfe, 0xff, 0xdf, 0xff,
	0x1b, 0xad, 0x34, 0xd0, 0x9d, 0xe9, 0xa2, 0xd0, 0xea, 0x6a, 0x5d, 0x6a, 0xa3, 0xe9, 0x61, 0xa3,
	0x2e, 0xe6, 0x70, 0x34, 0xde, 0xdc, 0xcb, 0x52, 0x49, 0x23, 0x2b, 0x37, 0xf6, 0x7d, 0xb5, 0xd0,
	0x94, 0xc2, 0x13, 0xf3, 0x79, 0x2d, 0xcf, 0x9c, 0x73, 0xe7, 0xb2, 0x9d, 0xd4, 0xb3, 0xf5, 0x56,
	0x6a, 0xa1, 0xcf, 0x5a, 0x8d, 0x67, 0x67, 0xfa, 0x16, 0xfa, 0x33, 0x5d, 0xac, 0x4b, 0x59, 0x55,
	0x72, 0x2e, 0xea, 0x78, 0xff, 0xdc, 0xb9, 0xec, 0x26, 0xbd, 0xff, 0xb6, 0x05, 0x5e, 0x7c, 0x85,
	0xa3, 0xb8, 0xd4, 0x85, 0x34, 0x4b, 0xb9, 0xf9, 0xb7, 0xe5, 0x3d, 0x9c, 0x98, 0x69, 0x99, 0x4b,
	0x23, 0x1e, 0x43, 0x9c, 0x1a, 0xf2, 0xa2, 0x49, 0xd9, 0x03, 0x94, 0x6d, 0xcd, 0xb4, 0x5a, 0xac,
	0xf2, 0x9d, 0x56, 0xab, 0x69, 0x35, 0xe9, 0xc3, 0xd6, 0xbb, 0x6f, 0x2d, 0xe8, 0x60, 0xb9, 0x9a,
	0x4b, 0x65, 0xd0, 0xfe, 0xa6, 0x07, 0x80, 0x28, 0xb2, 0x70, 0x1c, 0x46, 0xb7, 0x21, 0xd9, 0xfb,
	0xab, 0xe3, 0x24, 0x62, 0x3c, 0x4d, 0x89, 0x43, 0xdb, 0x70, 0x80, 0x28, 0x6e, 0x26, 0xa4, 0x45,
	0x8f, 0xa1, 0x6f, 0xa3, 0xec, 0x3a, 0xf0, 0x99, 0x60, 0x41, 0x94, 0x79, 0x64, 0x9f, 0x9e, 0xc2,
	0xb1, 0x35, 0x47, 0x77, 0xa9, 0xcf, 0xdc, 0x40, 0x4c, 0x5c, 0x36, 0xf2, 0x43, 0x4e, 0x0e, 0xe8,
	0x6b, 0x78, 0x85, 0x28, 0x3c, 0xee, 0xf9, 0xcc, 0x45, 0xee, 0xed, 0x3e, 0x39, 0xa4, 0x7d, 0xe8,
	0x20, 0x8a, 0x51, 0x94, 0xa2, 0x88, 0x23, 0x8f, 0x3c, 0xa5, 0xcf, 0xa1, 0x5d, 0x2f, 0xab, 0xe5,
	0x33, 0xfa, 0x12, 0x4e, 0x11, 0x05, 0x66, 0x61, 0xc8, 0x03, 0xe1, 0x71, 0xe6, 0xc6, 0x69, 0x16,
	0xb8, 0xe8, 0x47, 0x21, 0x69, 0xd3, 0x13, 0xa0, 0xb6, 0x7c, 0x17, 0xf3, 0x44, 0xdc, 0x08, 0x16,
	0x4d, 0xe2, 0x0c, 0x39, 0x81, 0x47, 0x7e, 0xc8, 0xf1, 0x36, 0x4a, 0xc6, 0xa4, 0x43, 0x29, 0xf4,
	0x10, 0xc5, 0xf8, 0x63, 0x2a, 0x52, 0xdf, 0xb2, 0x12, 0xd2, 0xbd, 0xfe, 0xf0, 0x63, 0x3b, 0x70,
	0x7e, 0x6e, 0x07, 0xce, 0xaf, 0xed, 0xc0, 0xf9, 0xfe, 0x7b, 0xb0, 0xf7, 0xe9, 0x4d, 0xbe, 0x32,
	0xcb, 0xcd, 0xfd, 0xd5, 0x4c, 0x17, 0xc3, 0x2f, 0xcb, 0xa9, 0xca, 0x17, 0x53, 0x25, 0x87, 0x85,
	0xac, 0xaa, 0x69, 0x2e, 0x87, 0xcd, 0xa9, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x54, 0x17,
	0x1d, 0x41, 0x02, 0x00, 0x00,
}

func (m *KubernetesAPIInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KubernetesAPIInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KubernetesAPIInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.CompressedInfo != nil {
		i -= len(m.CompressedInfo)
		copy(dAtA[i:], m.CompressedInfo)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.CompressedInfo)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Info != nil {
		i -= len(*m.Info)
		copy(dAtA[i:], *m.Info)
		i = encodeVarintCommon(dAtA, i, uint64(len(*m.Info)))
		i--
		dAtA[i] = 0x12
	}
	if m.Type != nil {
		i -= len(*m.Type)
		copy(dAtA[i:], *m.Type)
		i = encodeVarintCommon(dAtA, i, uint64(len(*m.Type)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PrometheusAPIInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PrometheusAPIInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PrometheusAPIInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.ConfigCompressedInfo != nil {
		i -= len(m.ConfigCompressedInfo)
		copy(dAtA[i:], m.ConfigCompressedInfo)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.ConfigCompressedInfo)))
		i--
		dAtA[i] = 0x12
	}
	if m.TargetCompressedInfo != nil {
		i -= len(m.TargetCompressedInfo)
		copy(dAtA[i:], m.TargetCompressedInfo)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.TargetCompressedInfo)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCommon(dAtA []byte, offset int, v uint64) int {
	offset -= sovCommon(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *KubernetesAPIInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != nil {
		l = len(*m.Type)
		n += 1 + l + sovCommon(uint64(l))
	}
	if m.Info != nil {
		l = len(*m.Info)
		n += 1 + l + sovCommon(uint64(l))
	}
	if m.CompressedInfo != nil {
		l = len(m.CompressedInfo)
		n += 1 + l + sovCommon(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PrometheusAPIInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TargetCompressedInfo != nil {
		l = len(m.TargetCompressedInfo)
		n += 1 + l + sovCommon(uint64(l))
	}
	if m.ConfigCompressedInfo != nil {
		l = len(m.ConfigCompressedInfo)
		n += 1 + l + sovCommon(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovCommon(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCommon(x uint64) (n int) {
	return sovCommon(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *KubernetesAPIInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KubernetesAPIInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KubernetesAPIInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Type = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Info = &s
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompressedInfo", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CompressedInfo = append(m.CompressedInfo[:0], dAtA[iNdEx:postIndex]...)
			if m.CompressedInfo == nil {
				m.CompressedInfo = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCommon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PrometheusAPIInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PrometheusAPIInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PrometheusAPIInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetCompressedInfo", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetCompressedInfo = append(m.TargetCompressedInfo[:0], dAtA[iNdEx:postIndex]...)
			if m.TargetCompressedInfo == nil {
				m.TargetCompressedInfo = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfigCompressedInfo", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConfigCompressedInfo = append(m.ConfigCompressedInfo[:0], dAtA[iNdEx:postIndex]...)
			if m.ConfigCompressedInfo == nil {
				m.ConfigCompressedInfo = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCommon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCommon(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCommon
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCommon
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCommon
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCommon
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCommon        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCommon          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCommon = fmt.Errorf("proto: unexpected end of group")
)
